version: '3.1'

services:
    zoo:
      image: zookeeper
      restart: on-failure
      hostname: zoo
      ports:
        - 2181:2181
      environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

    rmq:
        image: rabbitmq:3.8.3-alpine

    master:
        build:
            context: .
            dockerfile: Dockerfile

    slave:
        build:
            context: .
            dockerfile: Dockerfile

    sqlite3:
        image: nouchka/sqlite3:latest

    orchestrator:
        build:
            context: .
            dockerfile: Dockerfile
        command: sh -c "sleep 20 && python3 -u database.py"
        ports:
            - "80:80"
        volumes:
            - .:/code
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock

        links:
            - rmq
            - sqlite3
        depends_on:
            - rmq
            - sqlite3
        restart: on-failure
        

    

  
